### ISSUE TITLE
custom domain

### ISSUE THREAD

**Issue by Skydiver-Web** [jchabin/jchabin.github.io#1]
hi this is blocked at my school but a lot of my friends want to play so can I add my own custom domain so we can play please

**Comment by jchabin** [comment]
For security reasons, I can't make my FireBase databases open to be accessed from every URL. However, it should be easy to [fork this repository](https://github.com/jchabin/cars), use Github Pages to host it on whatever domain you want, and replace the [FireBase configuration](https://github.com/jchabin/cars/blob/71dcbf80ca7046ccc835938323da7dce87fe217d/script.js#L14-L68) to one that points to your own FireBase Realtime Databases.

The configurations I'm using are mostly the defaults, but with read/write rules set to
```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```
for each database, and with [anonymous authentication](https://firebase.google.com/docs/auth/web/anonymous-auth) enabled for the project. Once you have that set up for your own FireBase project, you can create a new web app inside that project, and copy over your `firebaseConfig` JSON object.
